version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
     - 8080:80
     - 8443:443
    volumes:
      - /home/lex/project1/html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/:/etc/nginx/certs/
    restart: always

  whoami:
    image: traefik/whoami
